#!/bin/sh -e



export GOPATH=${PWD}/Godeps/_workspace
export GOBIN=${PWD}/bin

if [ ! -h $GOPATH/src/github.com/coreos/etcdctl ]; then
    mkdir -p $GOPATH/src/github.com/coreos/
    ln -s ${PWD} $GOPATH/src/github.com/coreos/etcdctl
fi

eval $(go env)

go install github.com/coreos/etcdctl
