#!/bin/sh -e

if [ ! -h src/github.com/coreos/etcdctl ]; then
	mkdir -p src/github.com/coreos/
	ln -s ../../.. src/github.com/coreos/etcdctl
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go install github.com/coreos/etcdctl
