#!/bin/sh

# Get GOPATH, etc from build
. ./build

go test -i ./command
go test -v ./command
go test -v #ensure that there are 3 instances of etcd running locally on your machine then uncomment this line.  
